- hosts: db

  gather_facts: yes

  become: true

  tasks:
    - name: Installing MongoDB
      apt: pkg=mongodb state=present

    - name: Adding New configurations to mongod.conf file
      shell: |
        sudo rm /etc/mongodb.conf
        sudo touch /etc/mongodb.conf
        sudo chmod 666 /etc/mongodb.conf
        cd /etc
        echo "# mongodb.conf

          storage:
            dbPath: /var/lib/mongodb
            journal:
              enabled: true

          systemLog:
            destination: file
            logAppend: true
            path: /var/log/mongodb/mongod.log

          net:
            port: 27017
            bindIp: 0.0.0.0" >> mongodb.conf
         sudo systemctl restart mongodb

# where do we want to install
- hosts: web

    apt: pkg=nginx state=present

  - name: nginx reverse proxy
    shell:  |
    shell: |
      sudo unlink /etc/nginx/sites-enabled/default
      cd /etc/nginx/sites-available
      sudo touch reverse-proxy.conf
        listen 80;
        server_name development.local;
        location / {
            proxy_pass http://127.0.0.1:3000/;
        }
      }" >> reverse-proxy.conf
      sudo ln -s /etc/nginx/sites-available/reverse-proxy.conf /etc/nginx/sites-enabled/reverse-proxy.conf
      sudo service nginx restart
      sudo nginx -t
      sudo systemctl restart nginx
  - name: Install Nodejs
  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install npm
  - name: Install NPM
    apt: pkg=npm state=present


  - name: Install NPM modules
    shell: |
      npm install -g npm@latest
      npm install mongoose -y
# Downloading pm2
  - name: Install pm2
    npm:
      name: pm2
      global: yes



  - name: Running App On Web Virtual Machine
  - name: set up app
    shell: |
      cd app
      sudo npm install -g npm
      cd app/
      npm install
      node seeds/seed.js
      pm2 stop all
      pm2 kill
      pm2 start app.js
    environment:
      DB_HOST: mongodb://vagrant@192.168.33.11:27017/posts?authSource=admin
